- pages/api/manifest.ts
> Webhooks are always active

- pages/index.tsx
Generate command doesn't exist
> Use correct command name

- package.json
see: https://nextjs.org/docs/deployment\#nodejs-server
> "next start" just start NodeJS server to serve assets build in "next build"

- lib/environment.ts
> Fixing name of environment variable holding authToken in Vercel

- pages/api/manifest.ts
- pages/configuration.tsx
- pages/orders.tsx
Plus example of Dashboard extension (be aware, that it requires appUrl to be set, to make extension routable)
> [SALEOR-6519] Orders moved away from configurationUrl

- pages/api/manifest.ts
* forcing subscription to exist
* infering event type based on types generated from GraphQL schema
> Improved webhooks inference

- package.json
- pages/api/manifest.ts
- pages/api/register.ts
- pages/api/webhooks/order-created.ts
- pnpm-lock.yaml
- simpler HTTP handler signature: `Request => Response`
- an abstraction that allows to target other runtimes (e.g. Deno, Cloudflare)
- composable middleware pipelines with TypeScript typings
> Move common functionality to Apps SDK

- pages/api/configuration/orders.ts
- pages/api/number-of-orders.ts
- pages/orders.tsx
* set default numberOfOrders
* rename api/orders to api/number-of-orders
> Refactor orders - make it work by default

- package.json
The Saleor App configuration required for publishing is available under the `saleorApp` field in the `package.json`. The `saleor app publish` command reads that an issue a pull request to the repository that holds all Saleor Apps available in the Saleor marketplace.
> Add config for Saleor App publishing flow

- components/AccessWarning/AccessWarning.tsx
- components/AuthorizedPage/AuthorizedPage.tsx
- components/LoadingPage/LoadingPage.tsx
- components/LoadingPage/styles.ts
- components/PageMiddleware/PageMiddleware.tsx
- lib/middlewares.ts
- package.json
- pages/_app.tsx
- pages/configuration.tsx
- pages/index.tsx
- pnpm-lock.yaml
- types.ts
- utils/misc.ts
- utils/useIsMounted.ts
- utils/useToken.ts
* Creates a pages middleware that checks if app is in iframe and if token is valid
* Adds loading component and warning component
I would really appreciate feedback :)
> Create a message when app is accessed outside of dashboard

- package.json
- pages/configuration.tsx
- pnpm-lock.yaml
- utils/useDashboardNotifier.ts
Before merge this PR needs to be merged and released - https://github.com/saleor/app-bridge/pull/20
> Send notifications via app-bridge

- lib/environment.ts
The deployment to Vercel can be initiated **not only** from the marketplace (as the current env names suggest), but also from other places e.g. CLI, manually, via `git push`, etc. The names suggested here better describe the purpose of these env variables.
https://app.clickup.com/t/2549495/SALEOR-7616
> Better env names for the deployment of Saleor Apps

- README.md
- package.json
- pnpm-lock.yaml
- saleor-app.ts
> Add env variable with APL choice

- .github/workflows/prepare-prod-release.yml
- .github/workflows/release-prod.yml
Explore automatic PR canary->main to improve prod release flow
> Add Github workflow that automate release PRs

- src/pages/index.tsx
> Add quick install form

- .github/workflows/manage-example-branches.yml
Add token argument to the example branch labeling action
> Add token to the labeler action

- README.md
Fixed things I found while using the template
> Update link to the CLI reference, added a missing command

- README.md
- src/pages/index.tsx
- src/styles/globals.css
We received feedback from @aniav about the difficulties in making the first steps with apps. This PR is one of the attempts to improve it.
- Linguistic fixes to the `README.md`.
- Added some extra content to the template's introductory page. It now includes instructions on installing the app in the dashboard, links to Next.js documentation, and the "tunneling the apps" article. Some small fixes with it as well.
> Documentation improvements

- README.md
Renamed in https://github.com/saleor/saleor-cli/pull/645
> Fix docs for `app create` -> `app template`

- .npmrc
- package.json
Update PNPM to the newest version. No lockfile changes
> Update PNPM to 9.12.3

- next-env.d.ts
- package.json
- pnpm-lock.yaml
- src/pages/api/manifest.ts
- src/pages/api/protected.ts
- src/pages/api/register.ts
- src/saleor-app.ts
This is a testing branch that dogfoods `@saleor/app-sdk@1` before it's released
> Update app-sdk to @v1
